# Generated by Django 4.2.9 on 2024-02-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
