# Generated by Django 4.2.9 on 2024-02-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_Number',
            new_name='phone_number',
        ),
    ]
