# Generated by Django 4.2.9 on 2024-02-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_cover_product_product_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
