# Generated by Django 4.2.9 on 2024-02-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_cart_created_at_alter_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
